languageCode: 'fr'
baseURL: https://www.safe-n-tech.org/
removePathAccents: true

params:
  seo:
    author: MMI Bordeaux
    title: "Safe N Tech : Votre boussole pour un web sécurisé"
    desc: "Safe N Tech : La web-application de cybersécurité qui vous guide vers une meilleure sécurité en ligne. Bénéficiez de notre checklist détaillée, de quiz interactifs, d’un glossaire et d'informations claires pour renforcer votre protection numérique avec les bonnes pratiques."
    subject: "cybersecurity"
    url: https://www.safe-n-tech.org
    hero: /sprites/hero-min.jpg
    logo: /sprites/logo-min.png

frontmatter:
  slug:
    - "uuid"

taxonomies:
  # disable all taxonomies

permalinks:
  thematiques: /:section/:title/
  vulnerabilities: /:section/:title/
  good-practices: /good-practices/:slug/

menu:
  header:
    - identifier: thematiques
      weight: 1
      name: Checklist
      title: thématiques
      url: /thematiques/
    - identifier: quizz
      weight: 2
      name: Me tester
      title: quiz
      url: /quizz/
    - identifier: definitions
      weight: 5
      name: Glossaire
      title: glossaire
      url: /definitions/
    - identifier: Mille Bugs
      weight: 5
      name: Mille Bugs
      title: mille bugs
      url: /mille-bugs/
    - identifier: Fuite données
      weight: 6
      name: Mes données ont-elles fuité ?
      title: mes-donnees-ont-elles-fuite
      url: /mes-donnees-ont-elles-fuite/

sitemap:
  changeFreq: ""
  disable: false
  filename: sitemap.xml
  priority: -1

backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

deployment:
  ## CACHE
  matchers:
    - pattern: "^.+\\.(woff2|woff|svg|ttf|otf|eot|js|css)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: true
    - pattern: "^.+\\.(png|jpg|jpeg|gif|webp)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: false
  ## DEUXFLEURS
  targets:
    - name: "production"
      URL: "s3://www.safe-n-tech.org?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage&awssdk=v1"
