languageCode: 'fr'
baseURL: https://safe-n-tech.netlify.app/
removePathAccents: true

params:
  seo:
    author: MMI Bordeaux
    title: "Safe n' Tech : Votre boussole pour un web sécurisé"
    desc: "Safe n' Tech : La web-application de cybersécurité qui vous guide vers une meilleure sécurité en ligne. Bénéficiez de notre checklist détaillée, de quiz interactifs, d’un glossaire et d'informations claires pour renforcer votre protection numérique avec les bonnes pratiques."
    subject: "cybersecurity"
    url: https://safe-n-tech.netlify.app
    hero: /sprites/hero-min.jpg
    logo: /sprites/logo-min.png

taxonomies:
  # disable all taxonomies

permalinks:
  thematiques: /:section/:title/
  vulnerabilities: /:section/:title/
  good-practices: /:section/:title/

name: vulnerabilities
slug: "{{fields.uuid}}"
label: Vulnérabilités
label_singular: Vulnérabilité
folder: content/vulnerabilities
create: true
editor:
  preview: false
filter:
  field: "visibleInCms"
  value: true
fields:
  - label: "Visible"
    name: "visibleInCms"
    widget: hidden
    default: true
  - label: 'UUID'
    name: 'uuid'
    widget: uuid
    prefix: vulnerability
  - label: Titre
    name: title
    pattern:
      - '.{0,100}'
      - "Maximum 100 caractères"
  - label: Thématique
    name: thematique
    widget: relation
    collection: thematiques
    search_fields:
      - "title"
    value_field: uuid
    display_fields:
      - "title"
  - label: Risques
    name: risks
    widget: list
    required: false
  - label: Bonnes pratiques
    name: goodPractices
    widget: relation
    collection: good-practices
    search_fields:
      - "title"
    value_field: uuid
    display_fields:
      - "title"
    multiple: true
    required: false
  - label: Définitions
    name: definitions
    widget: relation
    collection: definitions
    search_fields:
      - "title"
    value_field: uuid
  - label: "Ne pas faire"
    name: dontDo
    widget: markdown
    required: false

menu:
  header:
    - identifier: thematiques
      weight: 1
      name: Checklist
      title: thématiques
      url: /thematiques/
    - identifier: quizz
      weight: 2
      name: Test
      title: quiz
      url: /quizz/
    - identifier: definitions
      weight: 5
      name: Glossaire
      title: glossaire
      url: /definitions/
    - identifier: Mille Bugs
      weight: 5
      name: Mille Bugs
      title: mille bugs
      url: /mille-bugs/

sitemap:
  changeFreq: ""
  disable: false
  filename: sitemap.xml
  priority: -1

backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow