languageCode: 'fr'
baseURL: https://www.safe-n-tech.org/
removePathAccents: true

params:
  seo:
    author: MMI Bordeaux
    title: "Safe N Tech : Votre boussole pour un web sécurisé"
    desc: "Safe N Tech : La web-application de cybersécurité qui vous guide vers une meilleure sécurité en ligne. Bénéficiez de notre checklist détaillée, de quiz interactifs, d’un glossaire et d'informations claires pour renforcer votre protection numérique avec les bonnes pratiques."
    subject: "cybersecurity"
    url: https://www.safe-n-tech.org
    hero: /sprites/hero-min.jpg
    logo: /sprites/logo-min.png

frontmatter:
  slug:
    - "uuid"

taxonomies:
  # disable all taxonomies

permalinks:
  thematiques: /:section/:title/
  good-practices: /good-practices/:slug/

menu:
  header:
    - identifier: je-suis
      weight: 10
      name: "Je suis ..."
      url: ""
    - identifier: professionnel
      parent: je-suis
      weight: 11
      name: Professionnel
      url: /aide-pro/
    - identifier: particulier
      parent: je-suis
      weight: 12
      name: Particulier
      url: ""
    - identifier: mineurs
      parent: particulier
      weight: 13
      name: "Mineurs / Ados"
      url: /mineurs/
    - identifier: parents
      parent: particulier
      weight: 14
      name: Parent
      url: /parents/
    - identifier: seniors
      parent: particulier
      weight: 15
      name: Senior
      url: /seniors/
    - identifier: me-tester
      weight: 20
      name: Me tester
      url: ""
    - identifier: quizz-culture-generale
      parent: me-tester
      weight: 21
      name: "Culture générale cybersécurité"
      url: /quizz-culture-generale/
    - identifier: quizz-hygiene
      parent: me-tester
      weight: 22
      name: "Hygiène numérique"
      url: /quizz/
    - identifier: aide-pro
      weight: 30
      name: Aide Pro
      url: /aide-pro/
    - identifier: checklist
      weight: 35
      name: "Checklist"
      url: /thematiques/
    - identifier: boite-a-outils
      weight: 40
      name: "Boîte à outils"
      url: /boite-a-outils/
    - identifier: liens-utiles
      weight: 45
      name: "Liens utiles"
      url: /liens-utiles/
    - identifier: verification
      weight: 46
      name: "Vérification"
      url: /verification/
    - identifier: mille-bugs
      weight: 50
      name: Mille Bugs
      url: /mille-bugs/
    - identifier: je-suis-victime
      weight: 65
      name: "Je suis victime"
      url: /je-suis-victime/
    - identifier: definitions
      weight: 70
      name: Glossaire
      url: /definitions/


sitemap:
  changeFreq: ""
  disable: false
  filename: sitemap.xml
  priority: -1

backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

deployment:
  ## CACHE
  matchers:
    - pattern: "^.+\\.(woff2|woff|svg|ttf|otf|eot|js|css)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: true
    - pattern: "^.+\\.(png|jpg|jpeg|gif|webp)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: false
  ## DEUXFLEURS
  targets:
    - name: "production"
      URL: "s3://www.safe-n-tech.org?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage&awssdk=v1"
