[build]
publish = "public"
command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.133.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"