[build]
  publish = "public"
  command = "yarn run build"

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"
  MISE_DEFAULT_VERSION = "hugo-extended@0.145.0"
  MISE_VERBOSE = "1"

[context.production.environment]
  HUGO_VERSION = "0.145.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
