backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/media'
public_folder: '/media'
locale: fr
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: thematiques
    slug: "{{fields.uuid}}"
    label: Catégories
    label_singular: Catégorie
    folder: content/thematiques
    create: true
    editor: { preview: false }
    filter: {field: "visibleInCms", value: true}
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true}
      - { label: 'UUID', name: 'uuid', widget: uuid, prefix: thematique }
      - { label: Titre, name: title, pattern: ['.{0,100}', "Maximum 100 caractères"] }
      - { label: Lien vidéo youtube, name: videoUrl, required: false }
      - { label: Sous titre, name: subtitle }
      - { label: Description, name: description }




  - name: vulnerabilities
    slug: "{{fields.uuid}}"
    label: Vulnérabilités
    label_singular: Vulnérabilités
    folder: content/vulnerabilities
    create: true
    editor: { preview: false }
    filter: { field: "visibleInCms", value: true }
    view_groups:
      - label: Catégorie
        field: thematiques
    view_filters:
      - label: Boîte mail
        field: thematiques
        pattern: Boîte mail
      - label: Déplacements
        field: thematiques
        pattern: Déplacements
      - label: Données confidentielles
        field: thematiques
        pattern: Données confidentielles
      - label: Droit résiduel à la vie privée
        field: thematiques
        pattern: Droit résiduel à la vie privée
      - label: Mise à jour
        field: thematiques
        pattern: Mise à jour
      - label: Mots de passe
        field: thematiques
        pattern: Mots de passe
      - label: Paiement en ligne
        field: thematiques
        pattern: Paiement en ligne
      - label: Réseaux sociaux
        field: thematiques
        pattern: Réseaux sociaux
      - label: Téléchargements et ingénierie sociale
        field: thematiques
        pattern: Téléchargements et ingénierie sociale
      - label: Wifi et bluetooth
        field: thematiques
        pattern: Wifi et bluetooth
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true }

      - { label: 'UUID', name: 'uuid', widget: uuid, prefix: vulnerability }

      - { label: Titre, name: title, pattern: ['.{0,100}', "Maximum 100 caractères"] }

      - label: Thématique
        name: thematique
        widget: relation
        collection: thematiques
        search_fields: ["title"]
        value_field: uuid
        display_fields: ["title"]

      - label: Risques
        name: risks
        widget: list
        required: false

      - label: Bonnes pratiques
        name: goodPractices
        widget: relation
        collection: good-practices
        search_fields: [ "title" ]
        value_field: uuid
        display_fields: [ "title" ]
        multiple: true
        required: false

      - label: Définitions
        name: definitions
        widget: relation
        collection: definitions
        search_fields: [ "title" ]
        value_field: uuid
        display_fields: [ "title" ]
        multiple: true
        required: false

      - { label: "Ne pas faire", name: dontDo, widget: markdown, required: false }

  - name: good-practices
    slug: "{{fields.slug | default: fields.uuid}}"
    label: Bonnes pratiques
    label_singular: Bonne pratique
    folder: content/good-practices
    create: true
    editor: { preview: false }
    filter: { field: "visibleInCms", value: true }
    view_groups:
      - label: Catégorie
        field: thematiques
    view_filters:
      - label: Boîte mail
        field: thematiques
        pattern: Boîte mail
      - label: Déplacements
        field: thematiques
        pattern: Déplacements
      - label: Données confidentielles
        field: thematiques
        pattern: Données confidentielles
      - label: Droit résiduel à la vie privée
        field: thematiques
        pattern: Droit résiduel à la vie privée
      - label: Mise à jour
        field: thematiques
        pattern: Mise à jour
      - label: Mots de passe
        field: thematiques
        pattern: Mots de passe
      - label: Paiement en ligne
        field: thematiques
        pattern: Paiement en ligne
      - label: Réseaux sociaux
        field: thematiques
        pattern: Réseaux sociaux
      - label: Téléchargements et ingénierie sociale
        field: thematiques
        pattern: Téléchargements et ingénierie sociale
      - label: Wifi et bluetooth
        field: thematiques
        pattern: Wifi et bluetooth
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true }

      - { label: 'UUID', name: 'uuid', widget: uuid, prefix: "good-practice" }

      - { label: Titre, name: title, pattern: ['.{0,100}', "Maximum 100 caractères"] }

      - { label: Slug court (automatiquement utilisé dans l’URL), name: slug, required: true, pattern: ['^.{0,60}$', "Maximum 60 caractères"] }

      - label: Thématique
        name: thematique
        widget: relation
        collection: thematiques
        search_fields: [ "title" ]
        value_field: uuid
        display_fields: [ "title" ]

      - label: Définitions
        name: definitions
        widget: relation
        collection: definitions
        search_fields: [ "title" ]
        value_field: uuid
        display_fields: [ "title" ]
        multiple: true
        required: false

      - label: Niveau
        name: niveau
        widget: select
        options:
          - { label: Basique, value: basique }
          - { label: Essentiel, value: essentiel }
          - { label: Avancé, value: avance }
        required: true

      - { label: Outil recommandé, name: tool, required: false, widget: text }



  - name: definitions
    slug: "{{fields.uuid}}"
    label: Définitions
    label_singular: Définition
    folder: content/definitions
    create: true
    editor: { preview: false }
    filter: { field: "visibleInCms", value: true }
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true }

      - { label: 'UUID', name: 'uuid', widget: uuid, prefix: definition }

      - { label: Titre, name: title, pattern: ['.{0,100}', "Maximum 100 caractères"] }

      - { label: Contenu, name: contenu, required: true }




  - name: questions
    slug: "{{fields.uuid}}"
    label: Questions
    label_singular: Question
    folder: content/questions
    create: true
    editor: { preview: false }
    filter: { field: "visibleInCms", value: true }
    identifier_field: text
    view_groups:
      - label: Catégorie
        field: thematiques
    view_filters:
      - label: Boîte mail
        field: thematiques
        pattern: Boîte mail
      - label: Déplacements
        field: thematiques
        pattern: Déplacements
      - label: Données confidentielles
        field: thematiques
        pattern: Données confidentielles
      - label: Droit résiduel à la vie privée
        field: thematiques
        pattern: Droit résiduel à la vie privée
      - label: Mise à jour
        field: thematiques
        pattern: Mise à jour
      - label: Mots de passe
        field: thematiques
        pattern: Mots de passe
      - label: Paiement en ligne
        field: thematiques
        pattern: Paiement en ligne
      - label: Réseaux sociaux
        field: thematiques
        pattern: Réseaux sociaux
      - label: Téléchargements et ingénierie sociale
        field: thematiques
        pattern: Téléchargements et ingénierie sociale
      - label: Wifi et bluetooth
        field: thematiques
        pattern: Wifi et bluetooth
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true }

      - { label: 'UUID', name: 'uuid', widget: uuid, prefix: question }

      - { label: Texte, name: text, pattern: ['.{0,100}', "Maximum 100 caractères"] }

      - { label: Correction, name: correction }

      - label: Bonnes pratiques
        name: goodPractices
        widget: relation
        collection: good-practices
        search_fields: [ "title" ]
        value_field: uuid
        display_fields: [ "title" ]
        multiple: true
        required: false

      - label: Thématique
        name: thematique
        widget: relation
        collection: thematiques
        search_fields: [ "title" ]
        value_field: uuid
        display_fields: [ "title" ]
        required: false

      - label: Choix
        name: choices
        widget: "list"
        fields:
          - { label: Text, name: text }
          - { label: Bonne réponse, name: isCorrect, widget: boolean, default: false, required: false }
